add redaction info to report
opensafely-core/interactive-templates pull request #207
Opened 2023-08-08 16:49 UTC by LFISHER7

Fixes #158

2023-08-10 15:53 UTC, HelenCEBM requested changes
couple of small fixes required..
Out of context of the results, these read a bit odd e.g. why have we suppressed counts less than 50 in one place but less than 10 in others? And why do we round to nearest 10 generally but nearest 7 in some cases?

2023-08-10 15:53 UTC, HelenCEBM commented on interactive_templates/templates/v2/analysis/report_template.html
> +                        Codes with a count less than are suppressed to reduce the risk of disclosure of patient identifiable information.
less than what?

2023-08-10 15:53 UTC, HelenCEBM commented on interactive_templates/templates/v2/analysis/report_template.html
> +                        They are then rounded to the nearest 7, before being used to calculate the percetage make-up.
```suggestion
                        They are then rounded to the nearest 7, before being used to calculate the percentage make-up.
```

2023-08-10 15:53 UTC, HelenCEBM commented on interactive_templates/templates/v2/analysis/report_template.html
> +                        Codes with a count less than are suppressed to reduce the risk of disclosure of patient identifiable information.
less than what?

2023-08-10 15:53 UTC, HelenCEBM commented on interactive_templates/templates/v2/analysis/report_template.html
> +                        They are then rounded to the nearest 7, before being used to calculate the percetage make-up.
```suggestion
                        They are then rounded to the nearest 7, before being used to calculate the percentage make-up.
```

2023-08-10 16:33 UTC, LFISHER7 commented
Thanks. I'll make the redaction consistent and will update here

2023-08-11 09:12 UTC, LFISHER7 commented
I've updated this so the redaction approach is to redact counts <=10 and then round to nearest 10. The only exception is in the event counts, where counts are rounded to the nearest 100 because they're high level counts so the accuracy is less important

2023-08-11 10:13 UTC, HelenCEBM approved these changes
Looks good. Personally I think it would be neater not to suppress values equal to 10, otherwise when we show a 10 it actually only represents values 11-14, but either way is fine!

2023-08-11 10:51 UTC, LFISHER7 commented
Good point! I've removed redaction of counts equal to 10.

2023-08-11 10:56 UTC, merged